### ISSUE TITLE
Footer is wider than the viewport

### ISSUE THREAD

**Issue by belcurv** [ursa-majors/co-ment#214]
Should be an easy fix. I think it's as simple as changing `_footer.scss`

From
```css
.footer {
    width:100vw;
    ...
}
```

to
```css
.footer {
    width:100%;
    ...
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/17347977/31034652-8f19a6e8-a52a-11e7-9521-556a3cfaf55d.png)
